#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PlatformSpecifics.Droid.Resource", IsApplication=true)]

namespace PlatformSpecifics.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010001
			public const int csharp = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int delete = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int icon = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int monkeyface = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int reminders = 2130771973;
			
			// aapt resource value: 0x7F010000
			public const int XamarinLogo = 2130771968;
			
			// aapt resource value: 0x7F010006
			public const int xaml = 2130771974;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F020000
			public const int AppCompatDialogStyle = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int MyTheme = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int MyTheme_Base = 2130837506;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
